Repository fioprotocol/fio, pull requests merged in 2020-07, with the labels that each got.

#204 Merge Gemini update Develop to Master
  CMakeLists.txt
  fio.contracts/contracts/fio.common/fioerror.hpp
  fio.contracts/contracts/fio.system/include/fio.system/native.hpp
  libraries/chain/apply_context.cpp
  libraries/chain/controller.cpp
  libraries/chain/eosio_contract.cpp
  libraries/chain/eosio_contract_abi.cpp
  libraries/chain/include/eosio/chain/apply_context.hpp
  libraries/chain/include/eosio/chain/contract_types.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/eosio_contract.hpp
  libraries/chain/include/eosio/chain/fioaction_object.hpp
  libraries/chain/include/eosio/chain/fioio/actionmapping.hpp
  libraries/chain/include/eosio/chain/types.hpp
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Labels: improvement

#196 Force lowercase searching of get_pub_address params
  libraries/chain/include/eosio/chain/fioio/fio_common_validator.hpp
  plugins/chain_plugin/chain_plugin.cpp
Labels: bug

#211 Fix bug inside fio_common_validator.hpp to enable lowercase setting
  libraries/chain/include/eosio/chain/fioio/fio_common_validator.hpp
Labels: bug

#212 Hotfix PR#121 into fio_common_validator.hpp
  libraries/chain/include/eosio/chain/fioio/fio_common_validator.hpp
Labels: bug

#210 add the actions to the actions table required for local dev test nets
  libraries/chain/controller.cpp
Labels: Testing
