Repository fioprotocol/fio, pull requests merged in 2020-05, with the labels that each got.

#121 Disable xferaddress/xferdomain action calls
  fio.contracts/contracts/fio.address/fio.address.cpp
Labels: Temp Fix

#119 add new endpoint for get_actor
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Labels: enhancement

#120 FIO Support for History Plugin
  fio.contracts/contracts/fio.common/keyops.hpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/config.hpp
  libraries/chain/include/eosio/chain/contract_types.hpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/chain/include/eosio/chain/exceptions.hpp
  libraries/chain/include/eosio/chain/transaction_context.hpp
  libraries/chain/transaction_context.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/history_api_plugin/history_api_plugin.cpp
  plugins/history_plugin/CMakeLists.txt
  plugins/history_plugin/history_plugin.cpp
  plugins/history_plugin/include/eosio/history_plugin/history_plugin.hpp
  plugins/http_plugin/http_plugin.cpp
Labels: bug, improvement

#126 Rebasing develop with master
  fio.contracts/contracts/fio.treasury/fio.treasury.cpp
Labels: bug

#131 Develop -> Master (v1.1.0)(fix)
  libraries/chain/include/eosio/chain/fioio/actionmapping.hpp
Labels: bug

#149 Revert Pub_K1 replace solution.
  libraries/chain/include/eosio/chain/fioio/pubkey_validation.hpp
  plugins/chain_plugin/chain_plugin.cpp
Labels: bug

#150 Revert Pub_K1 replace solution. (1.1.0)
  libraries/chain/include/eosio/chain/fioio/pubkey_validation.hpp
  plugins/chain_plugin/chain_plugin.cpp
Labels: bug
